# NAIVE BAYES

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("spam.csv")
df.head(3)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...

In [4]:
df["Category"] = df["Category"].map({"spam" : 1 , "ham" : 0})
df.head(3)

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...

In [5]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message , df.Category)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_test_count = v.transform(X_test)

In [7]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
model = MultinomialNB()
model.fit(X_train_count, y_train)
y_pred = model.predict(X_test_count)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(type(model))

Accuracy: 0.9856424982053122
<class 'sklearn.naive_bayes.MultinomialNB'>

In [8]:
import pickle
with open("NB_model.pkl", "wb") as file:
    pickle.dump(model, file)
print(type(model))
with open("vector.pkl", "wb") as file:
    pickle.dump(v, file)

<class 'sklearn.naive_bayes.MultinomialNB'>